/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d9d00518-aa2e-424e-856e-db4e4bfe37e7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gHyb3lNTl",
    "aws_user_pools_web_client_id": "qhs9vrpft2jhf976bsm5no5ud",
    "oauth": {},
    "aws_user_files_s3_bucket": "cws194106-prod",
    "aws_user_files_s3_bucket_region": "us-east-1"
};

export default awsmobile;
